### PR TITLE
feat: add SendWithContext

### PR DESCRIPTION
**Pull request by jonlundy**

### CODE REVIEW

**Comment by proofrock** [comment]
Hi Jon, sorry for the late reply - thank you so much for this! In the next days I'll review it. Could you kindly maybe add a test case? Thanks again!

**Comment by jonlundy** [comment]
@proofrock hey no worries! I have added a test case for a cancelled context.

**Comment by proofrock** [comment]
Excellent! Very nice, thanks a lot. Now I only have to figure out how to apply this to the `develop` branch...

**Comment by jonlundy** [comment]
Oh! i can switch to that one

**Comment by proofrock** [comment]
That would be great. If you can't, I'll try to rebase on develop, but the risk is that GitHub doesn't show your contribution on the project page... :-(

**Comment by jonlundy** [comment]
@proofrock done. cherry-picked over to develop

**Comment by proofrock** [comment]
Ok, done. Thanks a whole lot!!

**Comment by proofrock** [comment]
Tested and released. Again, many many thanks!

**Pull request merged**
